### ISSUE TITLE
상세 페이지 기획

### ISSUE THREAD

**Issue by SungJin-Jin** [LeePoongHo/group-purchase-react#25]

**Comment by rooge-jung** [comment]
라프텔을 기반으로 한다. 
[https://laftel.net/item/38968/%EB%B0%94%EB%9E%8C%EC%9D%B4-%EA%B0%95%ED%95%98%EA%B2%8C-%EB%B6%88%EA%B3%A0-%EC%9E%88%EB%8B%A4](url)
참조
header는 네비게이션 메뉴 탭.
body에서 top은 동일하게 간다. 
대신 평점 -> 가격과 공동구매 인원
middle에서 줄거리 ->  idea 좀...
에피소드 -> 상품 소개글
이어보면 좋을 애니 -> 상품 소개 이미지를 슬라이드?!
관련테마 -> 관련 상품 이미지
제작정보 태그는 생략!
